services:
  - type: web
    name: project-management-backend
    env: node
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 7d
      - key: FRONTEND_URL
        sync: false
